-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 15:24:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupomania` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `groupomania` ;

-- -----------------------------------------------------
-- Table `groupomania`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`users` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(10) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARBINARY(50) NOT NULL,
  PRIMARY KEY (`id`, `email`),
  UNIQUE INDEX `ind_uni_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`messages` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT NOT NULL,
  `attachement` VARCHAR(120) NULL DEFAULT NULL,
  `publication` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_userPost_numero` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_userMessages_numero`
    FOREIGN KEY (`user_id`)
    REFERENCES `groupomania`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`commentaires` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `publication` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_numero` (`message_id` ASC) VISIBLE,
  INDEX `fk_userCommentaires_numero` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_numero`
    FOREIGN KEY (`message_id`)
    REFERENCES `groupomania`.`messages` (`id`),
  CONSTRAINT `fk_userCommentaires_numero`
    FOREIGN KEY (`user_id`)
    REFERENCES `groupomania`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
